//
// ProgramItemRecentAirTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProgramItemRecentAirTime: Codable, JSONEncodable, Hashable {

    /** Program item ID */
    public var id: Int?
    /** Channel ID the program belongs to */
    public var channelID: Int?

    public init(id: Int? = nil, channelID: Int? = nil) {
        self.id = id
        self.channelID = channelID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case channelID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(channelID, forKey: .channelID)
    }
}

