//
// Channel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Channel: Codable, JSONEncodable, Hashable {

    /** Order of the channel in the TV Guide */
    public var orderNum: Int?
    /** Channel access and display number */
    public var accessNum: Int?
    /** Channel CallSIgn */
    public var callSign: String?
    /** Channel ID */
    public var id: Int?

    public init(orderNum: Int? = nil, accessNum: Int? = nil, callSign: String? = nil, id: Int? = nil) {
        self.orderNum = orderNum
        self.accessNum = accessNum
        self.callSign = callSign
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderNum
        case accessNum
        case callSign = "CallSign"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderNum, forKey: .orderNum)
        try container.encodeIfPresent(accessNum, forKey: .accessNum)
        try container.encodeIfPresent(callSign, forKey: .callSign)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

